development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: agc_development
  pool: 5
  username: agc
  password: agc

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: agc_production
  pool: 5
  username: agc
  password: agc

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: agc_test
  pool: 5
  username: agc
  password: agc

